{% set name = "bigdecimal" %}
{% set version = "3.2.3" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: ffd11d1ac67a0d3b2f44aec0a6487210b3f813f363dd11f1fcccf5ba00da4e1b

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'


about:
  home: https://rubygems.org/gems/bigdecimal
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: BigDecimal is a Ruby library for arbitrary-precision decimal arithmetic.
  doc_url: http://www.rubydoc.info/gems/bigdecimal
  dev_url: https://github.com/ruby/bigdecimal

extra:
  recipe-maintainers:
    - BIT-cypher
