{% set name = "bigdecimal" %}
{% set version = "3.2.2" %}
{% set sha256 "39085f76b495eb39a79ce07af716f3a6829bc35eb44f2195e2753749f2fa5adc" %}
{% set build = "1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: {{ sha256 }}

build:
  number: {{ build }}
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: True  # [win]

requirements:
  build:
      - {{ compiler('c') }}
      - {{ stdlib('c') }}
      - make
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'


about:
  home: https://rubygems.org/gems/bigdecimal
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: BigDecimal is a Ruby library for arbitrary-precision decimal arithmetic.
  doc_url: http://www.rubydoc.info/gems/bigdecimal
  dev_url: https://github.com/ruby/bigdecimal

extra:
  recipe-maintainers:
    - BIT-cypher
